version: '3.4'

services:
  askzenai:
    image: askzenai
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5555:5555
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/index.js"]
